### ISSUE TITLE
Consider Alternative Name to Prevent Unintentional Offense

### ISSUE THREAD

**Issue by ghost** [xfangfang/wiliwili#334]
The current name of this application has an unintentional phonetic similarity to an offensive phrase. It may be advisable to consider renaming it to something more neutral in order to avoid any potential misunderstandings or inadvertent offense. An alternative name could prevent distracting issues and allow the focus to remain solely on the application's functionality.

**Comment by xfangfang** [comment]
I'm sorry if the name of the application has caused you any confusion. Could you tell me in which language this name might be ambiguous? I'm also curious about the specific ambiguity.

wiliwili is a third-party client for a well-known Chinese website, [bilibili](https://www.bilibili.com). Both names are meaningless onomatopoeic words. The reason I chose this name is because the initial version of this software was released on the Nintendo Switch, so I chose the `wi` in the `switch` as part of the name, implying that this is a bilibili client designed for the switch. I also found on Wikipedia that wiliwili is a type of tree in Hawaii: https://en.wikipedia.org/wiki/Wiliwili

In the past month, 98.8% of users have used Chinese as the default language of the software. To my understanding of Mandarin Chinese, wiliwili does not have any offensive meaning, it is just a meaningless pronunciation.

We all encounter unintentional offenses between different languages more or less. One day I saw a clothing store in a mall, the name was: "诗婷" (if translated literally, it should be: Poetry Beauty, in Chinese this is usually a woman's name), but if you say it, the pronunciation is: `shi ting`(诗 -> shi, 婷 -> ting), I think this only adds some fun, because if you don't speak English, no one will understand it in the wrong direction.

**Comment by ghost** [comment]
The name 'wiliwili' can sound very similar to the English phrase 'willy willy' which is a British slang, potentially offensive term referring to male genitalia. The phonetic similarity to 'willy willy' in English could lead to unintended offense or immature jokes.

**Comment by ghost** [comment]
早上好。
首先，感谢您对此的解释。我知道这个客户端是Bilibili (B站?) 的一个第三方客户端，并且这个网站在中国有很大的影响力。当然，这个应用的名字在中文里面并没有任何的冒犯之意，但此名字在英语中很容易产生误解：若读音类似于 'Willie Willie'，此名的读音就会十分像英语中的一个用于描述男性生殖器的俚语 (willie/willy)。可能建议考虑将其重命名为更中性的名称，以避免任何潜在的误解或无心的冒犯。一个替代名称可以防止分心的问题，并让重点仍然集中在应用程序的功能上。

此致
Olaf Benjamin Sheeran 王启超

**Comment by xfangfang** [comment]
Thank you very much for the suggestion. As I mentioned earlier, 98.8% of the users of this application speak Chinese. I don't think it's a good idea to have the majority of existing users accept a new name just to avoid a homophone of an English slang.

**Comment by ghost** [comment]
嗯，确实。

**Comment by xfangfang** [comment]
Wow, so you're one of the users of this app? Which system do you use this software on? I didn't expect you to speak Chinese.

Changing the name is a complicated matter. Although there aren't many users of this application, it's also strenuous to get these people to accept a new name. The commonly used Chinese name for bilibili is "哔哩哔哩". I also named this software something similar, but it doesn't display on every platform. If it's read in Chinese, the pronunciation might not be that similar.

<img width="284" alt="image" src="https://github.com/xfangfang/wiliwili/assets/16631584/7813a451-929e-42c4-87c2-76d9a84ff842">

**Comment by ghost** [comment]
Yeah, I am on Fedora Silverblue/Flatpak :D. And yes I speak Chinese.

**Comment by xfangfang** [comment]
还有另外一个linux下的客户端，是官方客户端的移植修改版，你也可以使用看看：https://github.com/msojocs/bilibili-linux

**Comment by ghost** [comment]
Bilibili-Linux好像只有AppImage和二进制包，我不太喜欢AppImage（虽然我知道可以用Gear Lever把它加到应用菜单里），而二进制包就更加糟糕了（我尽量避免用rpm-ostree安装二进制包，毕竟Silverblue用的是不可写的运行时文件系统，用二进制包安装用户软件可以说是违反了它的设计原则）。我用WiliWili的原因之一是它有Flatpak版本。

**Comment by xfangfang** [comment]
原来如此，这个仓库貌似提供了bilibili-linux的flatpak包的构建，可以体验试试：https://github.com/madoka773/flatpak
